Testing

diff --git a/dnsedit b/dnsedit
--- a/dnsedit
+++ b/dnsedit
@@ -19,6 +19,7 @@ IP=''
 TYPE='A'
 OPERATION='Add'
 VERBOSE=''
+TTL=''
 
 ALLZONES=($(grep 'zone ' "$NAMEDCONF" | awk '{print $2}' | tr '[:upper:]' '[:lower:]'))
 
@@ -35,16 +36,18 @@ while [[ $# -gt 0 ]]; do
     ptr) TYPE='PTR' ;;
     ns) TYPE='NS' ;;
     cname) TYPE='CNAME' ;;
-    del) OPERATION='Del' ;;
+    del|rem|remove|rm) OPERATION='Del' ;;
     add) OPERATION='Add' ;;
     list|ls) OPERATION='List' ;;
     -v*) VERBOSE='yes' ;;
+    -ip) if [[ $2 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then IP=$2; else echo "Invalid IP specified"; exit 1; fi; shift ;;
     1*) IP=$1 ;;
     *)
       if [[ ${ALLZONES[@]} =~ \"$lc\" ]]; then ZONE=$lc
       elif [[ $lc =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then IP=$lc
       elif [[ ${ALLZONES[@]} =~ \"$lc.$BASE\" ]]; then ZONE=$lc.$BASE
       elif [[ $lc != ${lc/\./} ]]; then echo "$lc not valid zone or IP"
+      elif [[ $lc =~ ^[0-9]+$ ]]; then TTL=$lc
       elif [[ -z $ENTRY ]]; then ENTRY=$lc
       elif [[ -z $ENTRY2 ]]; then ENTRY2=$lc
       else
@@ -64,25 +67,43 @@ BOT="show\nsend"
 # Note: A blank line is processed as a send
 
 function doAddA() {
-  echo -e "${TOP}update add $ENTRY.$ZONE 86400 $TYPE $IP\n${BOT}" | nsupdate -k "$KEYFILE"
+  [[ -n $TTL ]] || TTL=86400
+  echo -e "${TOP}update add $ENTRY.$ZONE $TTL $TYPE $IP\n${BOT}" | nsupdate -k "$KEYFILE"
+}
+
+function doDelA() {
+  echo -e "${TOP}update del $ENTRY.$ZONE $TYPE $IP\n${BOT}" | nsupdate -k "$KEYFILE"
 }
 
 function doAddCNAME() {
+  [[ -n $TTL ]] || TTL=4800
   echo "not implemented"
 }
 
 function doAddPTR() {
-  echo -e "${TOPS}update add $PTRIP.in-addr.arpa. 4800 PTR $ENTRY.$ZONE\n${BOT}" | nsupdate -k "$KEYFILE"
+  [[ -n $TTL ]] || TTL=4800
+  echo -e "${TOPS}update add $PTRIP.in-addr.arpa. $TTL PTR $ENTRY.$ZONE\n${BOT}" | nsupdate -k "$KEYFILE"
+}
+
+function doDelPTR() {
+  echo -e "${TOPS}update del $PTRIP.in-addr.arpa. PTR $ENTRY.$ZONE\n${BOT}" | nsupdate -k "$KEYFILE"
 }
 
 function doAddNS() {
-  echo -e "${TOP}update add $ENTRY.$ZONE. 7200 $TYPE $ENTRY2.$ZONE\n${BOT}" | nsupdate -k "$KEYFILE"
+  [[ -n $TTL ]] || TTL=7200
+  echo -e "${TOP}update add $ENTRY.$ZONE. $TTL $TYPE $ENTRY2.$ZONE\n${BOT}" | nsupdate -k "$KEYFILE"
+}
+
+function doDelNS() {
+  echo -e "${TOP}update del $ENTRY.$ZONE. $TYPE $ENTRY2.$ZONE\n${BOT}" | nsupdate -k "$KEYFILE"
 }
 
 function isPTR() { [[ $TYPE == PTR ]]; }
 function isNS() { [[ $TYPE == NS ]]; }
 function isA() { [[ $TYPE == A ]]; }
 function isCNAME() { [[ $TYPE == CNAME ]]; }
+function isAdd() { [[ $OPERATION == 'Add' ]]; }
+function isDel() { [[ $OPERATION == 'Del' ]]; }
 
 function lookupZone() {
   grep "^$1.$ZONE" <<<$EXISTING_RECORDS
@@ -112,19 +133,25 @@ function check() {
   fi
   # Perform checks
   if [[ -z $ZONE ]]; then echo "You did not specify a zone"; return 1
-  elif [[ -z $ENTRY ]]; then echo "You did not specify a name to add"; return 1
+  elif [[ -z $ENTRY ]]; then echo "You did not specify a name to edit"; return 1
   elif isNS && [[ -z $ENTRY2 ]]; then echo "You did not specify a glue record to add"; return 1
   elif isNS && [[ -z $has_name2 ]]; then echo "Specified glue record '$ENTRY2' does not exist"; return 1
   elif [[ -z $IP ]] && ! isNS; then echo "You did not specify an IP to add"; return 1
-  elif [[ -n $has_ip ]] && ! isPTR; then echo "IP exists already $has_ip"; return 1
-  elif [[ -n $has_name ]] && ! isPTR; then echo "Name exists already $has_name"; return 1
+  elif (isAdd && [[ -n $has_ip ]] && ! isPTR); then echo "IP exists already $has_ip"; return 1
+  elif (isDel && [[ -z $has_ip ]]); then echo "Cannot find IP $IP to delete!"; return 1
+  elif (isAdd && [[ -n $has_name ]] && ! isPTR); then echo "Name exists already $has_name"; return 1
+  elif (isDel && [[ -z $has_name ]]); then ehco "Cannot find $ENTRY to delete it!"; return 1
   elif [[ -z $has_name ]] && isPTR; then echo "Name $ENTRY does not exist yet!"; return 1
-  elif (isA || isPTR) && [[ -z $ZONEPTR ]]; then echo "PTR Zone not found for $IP"; return 1
   elif isPTR && [[ -z $ZONEPTR ]]; then echo "Could not identify PTR zone for $IP"; return 1
   elif isPTR && [[ -n $has_ptr ]]; then echo "PTR record already exists!"; return 1
   fi
-  if isNS; then echo "Adding $TYPE $ENTRY to zone $ZONE stub $ENTRY2"
-  else echo "Adding $TYPE $ENTRY with IP $IP to zone $ZONE"; fi
+  # Warnings only
+  if (isA || isPTR) && [[ -z $ZONEPTR ]]; then echo "PTR Zone not found for $IP"; 
+  fi
+  if isAdd; then echo -n 'Adding'; elif isDel; then echo -n 'Deleting'; fi
+  echo " $TYPE $ENTRY "
+  if isNS; then echo "to zone $ZONE stub $ENTRY2"
+  else echo "with IP $IP to zone $ZONE"; fi
   read -p "Press <enter> to continue"
   # Return 0 to continue
   return 0
@@ -133,5 +160,5 @@ function check() {
 if [[ $OPERATION == List ]]; then
   dig +noquestion +nocmd +nocomments +nostat @$SERVERIP AXFR $ZONE | grep -w $TYPE
 elif check; then
-  eval doAdd${TYPE}
+  eval "do${OPERATION}${TYPE}"
 fi
